clients:
  global-weather:
    url: ~
    ssl:
      enabled: true
      keystore: ~
      keystore-password: ~
      keystore-type: JKS
      key-alias: ~
      key-password: ~
      truststore: ~
      truststore-password: ~
      verifyHostName: false